line-length = 80
indent-width = 4

[lint.per-file-ignores]
"__init__.py" = ["F401"]

[lint]
preview = true
fixable = true
select = ["E", "F", "I", "N", "C90"]

[format]
quote-style = "double"
