line-length = 80
indent-width = 4

[lint.per-file-ignores]
"__init__.py" = ["F401"]

[lint]
preview = true
fixable = []
select = ["E", "F", "N", "C90"] #добавить тег "I", имипорты в конце

[format]
quote-style = "double"
